# Generated by Django 3.2.16 on 2022-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialrecipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='cook_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipes',
            name='prep_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
