# Generated by Django 3.2.16 on 2022-12-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialrecipe', '0002_auto_20221229_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Hidden'), (3, 'Removed')], default=1),
        ),
    ]
