# Generated by Django 3.2.16 on 2023-01-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialrecipe', '0005_alter_userdetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='slug',
            field=models.SlugField(default='one', max_length=150),
            preserve_default=False,
        ),
    ]
