# Generated by Django 3.2.16 on 2023-01-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialrecipe', '0006_shoppinglist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitems',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
