# Generated by Django 3.2.16 on 2023-01-03 00:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialrecipe', '0007_auto_20230101_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_image',
            field=cloudinary.models.CloudinaryField(default='v1670885027/placeholder.jpg', max_length=255, verbose_name='image'),
        ),
    ]
