# Generated by Django 3.2.16 on 2023-01-17 20:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialrecipe', '0008_alter_userdetails_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitems',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
