# Generated by Django 3.2.16 on 2023-01-29 21:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialrecipe', '0009_alter_recipeitems_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_image',
            field=cloudinary.models.CloudinaryField(default='v1675027391/placeholder-recipe.png', max_length=255, verbose_name='image'),
        ),
    ]
