# Generated by Django 3.2.16 on 2023-02-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialrecipe', '0010_alter_recipes_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitems',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitems',
            name='list',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitems',
            name='unit',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='ShoppingListItems',
        ),
    ]
