# Generated by Django 3.2.16 on 2023-02-14 23:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialrecipe', '0013_alter_recipeimages_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_image',
            field=cloudinary.models.CloudinaryField(default='v1676418063/placeholder.webp', max_length=255, verbose_name='image'),
        ),
    ]
