# Generated by Django 3.2.16 on 2023-03-13 02:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialrecipe', '0014_alter_userdetails_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_image',
            field=cloudinary.models.CloudinaryField(default='placeholder-recipe', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
